community_online_submit/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

favicon_view = RedirectView.as_view(url='/static/form_1/img/favicon.ico', permanent=True)  # django2.2

# 修改后台站点头部和标题
admin.site.site_title = '社区活动报名后台管理系统'  # 站点标题
admin.site.site_header = '社区活动报名后台管理系统'  # 站点头部

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('activity_submit/', include('activity_submit.urls')),
                  path('', include('submit.urls'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

submit/urls.py
# -*- coding:utf-8 -*-
# @Author: syz
# @Time: 2022/11/11 13:52
# @File: urls.py
from django.urls.conf import path
from . import views

app_name = 'submit'

urlpatterns = [
    path('', views.new_person_request, name='new_person_request'),
    path('submit/<name>/<class_num>/<phone>/<qq_num>/<department>/', views.submit),
    path('new_person_request/', views.new_person_request, name='new_person_request'),
    path('new_person_submit/', views.new_person_submit, name='new_person'),
    path('community_person_request/', views.community_person_request, name='community_person_request'),
    path('community_person_submit/', views.community_person_submit, name='community_person_submit'),
]

activity_submit/models.py
from django.db import models

# Create your models here.
# 系统控制
from django.utils import timezone


class SystemControl(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name='调控器id')
    can_submit = models.BooleanField(default=False, verbose_name='是否可以报名')
    team_size = models.IntegerField(verbose_name='组队规模')

    def was_published_recently(self):
        now = timezone.now()
        return now

    was_published_recently.short_description = 'Published recently?'

    def __str__(self):
        return '系统控制'

    class Meta:
        verbose_name = '系统控制'
        verbose_name_plural = '系统控制'


# 活动信息
class Activity(models.Model):
    name = models.CharField(max_length=50, primary_key=True, verbose_name='活动名称')
    introduction = models.TextField(verbose_name='活动介绍')
    title = models.CharField(max_length=50, verbose_name='报名表标题')
    context = models.TextField(verbose_name='报名表说明')
    qq_QRcode = models.ImageField(upload_to='QRcode', verbose_name='群二维码')
    qq_num = models.CharField(max_length=20, verbose_name='群号码')
    background_img = models.ImageField(upload_to='background_img', verbose_name='背景图')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '活动信息'
        verbose_name = '活动信息'


# 参赛者
class Student(models.Model):
    name = models.CharField(max_length=10, verbose_name='姓名')
    stu_id = models.CharField(max_length=10, primary_key=True, verbose_name='学号')
    class_num = models.CharField(max_length=20, verbose_name='班级')
    academy = models.CharField(max_length=20, verbose_name='学院')
    qq_num = models.CharField(max_length=15, verbose_name='QQ号')
    phone = models.CharField(max_length=15, verbose_name='手机号')
    team_id = models.CharField(max_length=5, verbose_name='队伍号')
    is_leader = models.BooleanField(default=False, verbose_name='是否队长')
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name='报名时间')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = '参赛者'
        verbose_name = '参赛者'


# 学院专业
class AcademyClass(models.Model):
    academy = models.CharField(max_length=20, verbose_name='学院')
    class_name = models.CharField(max_length=20, primary_key=True, verbose_name='专业')

    def __str__(self):
        return self.class_name

    class Meta:
        verbose_name_plural = '学院专业'
        verbose_name = '学院专业'

submit/models.py
from django.db import models


# Create your models here.

class NewPerson(models.Model):
    name = models.CharField(max_length=10, verbose_name='姓名')
    sex = models.CharField(max_length=2, verbose_name='性别')
    phone = models.CharField(max_length=15, verbose_name='手机号', primary_key=True)
    address = models.TextField(verbose_name='住址')
    activity = models.CharField(max_length=10, verbose_name='活动')
    department = models.CharField(max_length=10, verbose_name='部门')
    changeable = models.CharField(max_length=2, verbose_name='是否接受调剂')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '社区新人'
        verbose_name_plural = '社区新人名单'


class CommunityPerson(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='编号')
    name = models.CharField(max_length=10, verbose_name='姓名')
    sex = models.CharField(max_length=2, verbose_name='性别')
    phone = models.CharField(max_length=15, verbose_name='手机号')
    address = models.TextField(verbose_name='住址')
    activity = models.TextField(verbose_name='活动')
    department = models.CharField(max_length=10, verbose_name='部门')
    department_job = models.CharField(max_length=10, verbose_name='部门职务')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '社区人员信息'
        verbose_name_plural = '社区人员信息表'

submit/views.py
from django.shortcuts import render, HttpResponse
from django.db.utils import IntegrityError
from .models import NewPerson, CommunityPerson


# Create your views here.
def new_person_request(request):
    return render(request, 'new_person.html')


def new_person_submit(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        sex = request.POST.get('sex')
        class_num = request.POST.get('class_num')
        school = request.POST.get('school')
        department = request.POST.get('department')
        phone = request.POST.get('phone')
        qq_num = request.POST.get('qq_num')
        changeable = request.POST.get('changeable')

        try:
            NewPerson.objects.get_or_create(
                name=name,
                sex=sex,
                class_num=class_num,
                school=school,
                department=department,
                phone=phone,
                qq_num=qq_num,
                changeable=changeable
            )
        except IntegrityError as e:
            return HttpResponse('提交出错，此手机号已有记录，且你提交的内容与记录内容有不同处，重复提交无效。如需修改信息请联系我们')
        '''
        print(name)
        print(sex)
        print(class_num)
        print(school)
        print(department)
        print(phone)
        print(qq_num)
        print(changeable)
        '''
        return render(request, 'thanks.html')
    else:
        return render(request, 'new_person.html')


def community_person_request(request):
    return render(request, 'kexie_person.html')


def submit(request, name, sex, class_num, school, phone, qq_num, department, changeable):
    NewPerson.objects.get_or_create(
        name=name,
        sex=sex,
        class_num=class_num,
        school=school,
        department=department,
        phone=phone,
        qq_num=qq_num,
        changeable=changeable
    )
    '''
    print('姓名：', name)
    print('性别：', sex)
    print('班级：', class_num)
    print('校区：', school)
    print('学号：', stu_id)
    print('手机号：', phone)
    print('QQ号：', qq_num)
    print('想去的部门：', department)
    print('是否服从调剂：', changeable)
    '''
    return HttpResponse('提交成功！')


def community_person_submit(request):
    if request.method == 'POST':
        sex = request.POST.get('sex')
        name = request.POST.get('name')
        address = request.POST.get('address')
        activity = request.POST.get('activity')
        department = request.POST.get('department')
        department_job = request.POST.get('department_job')
        phone = request.POST.get('phone')
        # print(name)
        # print(sex)
        # print(address)
        # print(activity)
        # print(department)
        # print(department_job)
        # print(phone)
        try:
            CommunityPerson.objects.get_or_create(
                name=name,
                sex=sex,
                department=department,
                department_job=department_job,
                address=address,
                activity=activity,
                phone=phone,
            )
        except IntegrityError as e:
            return HttpResponse('提交出错，此学号已有记录，且你提交的内容与记录内容有不同处，重复提交无效。如需修改信息请联系我们')

        return render(request, 'thanks.html')
    else:
        return render(request, 'kexie_person.html')

templates/error_multiple_submit.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>出错啦～</title>

    <link rel="stylesheet" href="{% static 'form_1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/tooplate.css' %}">
</head>

<body id="application" style="background-image: url(/activity_submit{{ background_img.url }})">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mt-5 mb-5 text-center">
                    <h3><b>重复提交</b></h3>
                    <p class="tm-form-description">{{ academy }} {{ class_num }}班的{{ name }}同学,</p>
                    <p class="tm-form-description">你已经报过名啦，请不要重复提交哦～</p>
                    <p class="tm-form-description">你的队伍号是{{ team_id }}</p>
                    <p class="tm-form-description">你的队伍成员有：</p>
                    {% for teammate_name in teammate_names %}
                        <p class="tm-form-description">{{ teammate_name.name }}</p>
                    {% endfor %}
                    <p class="tm-form-description">如果以上信息有误，请联系管理员修改～</p>
                    <br>
                    <p class="tm-form-description">QQ群号</p>
					<img width="200" src="/activity_submit{{ qq_QRcode.url }}" alt="二维码加载失败">
                </header>
            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                    欢迎加入科协大家庭，深入了解请访问-
					<a href="http://tw.cczu.edu.cn/dxskx/main.htm" target="_blank" title="科协官网">科协官网</a></p>
            </div>
        </footer>
    </div>

</body>

</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>社区活动线上报名</title>

    <link rel="shortcut icon" href="{% static 'form_1/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/tooplate.css' %}">
</head>

<body id="application" style="background-image: url(/activity_submit{{ background_img.url }})">
<div class="container">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
            <header class="mt-5 mb-5 text-center">
                <h3><b>{{ name }}</b></h3>
                <p class="tm-form-description">{{ introduction }}</p>
                <p class="tm-form-description">{{ qq_num }}</p>
                <img width="200" src="/activity_submit{{ qq_QRcode.url }}" alt="二维码加载失败">
            </header>
            <form action="{% url 'index' %}" method="post" enctype="multipart/form-data" class="tm-form-white tm-font-big">
                {% csrf_token %}
                <input id="id_teammate" name="teammate" value="队长" hidden>
                <div class="tm-bg-white tm-form-pad-big center">
                    <button type="submit" class="waves-effect btn-large btn-large-white">我是队长</button>
                </div>
            </form>
            <form action="{% url 'index' %}" method="post" enctype="multipart/form-data" class="tm-form-white tm-font-big">
                {% csrf_token %}
                <input id="id_teammate" name="teammate" value="队员" hidden>
                <div class="tm-bg-white tm-form-pad-big center">
                    <button type="submit" class="waves-effect btn-large btn-large-white">我是队员</button>
                </div>
            </form>
        </div>
    </div>
    <footer class="row tm-mt-big mb-3">
        <div class="col-xl-12 text-center">
            <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                欢迎加入科协大家庭，深入了解请访问-
                <a href="http://tw.cczu.edu.cn/dxskx/main.htm" target="_blank" title="科协官网">科协官网</a></p>
        </div>
    </footer>
</div>

</body>

</html>

templates/kexie_person.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>科仔信息系统</title>

    {% load static %}
    <link rel="stylesheet" href="{% static "form_1/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "form_1/css/materialize.min.css" %}">
    <link rel="stylesheet" href="{% static "form_1/css/tooplate.css" %}">
</head>

<body id="register" style="background-image: url({% static '/form_1/img/input-bg-01.jpg' %})">
<div class="container">
    <div class="row tm-register-row">
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 tm-register-col-l">
            <form action="{% url 'submit:community_person_submit' %}" method="post">
                {% csrf_token %}
                <div class="mb-2">
                    <label class="mr-4">
                        <input class="with-gap" name="sex" type="radio" value="男" required/>
                        <span>男</span>
                    </label>
                    <label class="mr-4">
                        <input class="with-gap" name="sex" type="radio" value="女" required/>
                        <span>女</span>
                    </label>
                </div>

                <div class="input-field">
                    <input placeholder="姓名" id="name" name="name" type="text" class="validate" required>
                </div>

                <div class="input-field">
                    <input placeholder="住址" id="address" name="address" type="text" class="validate">
                </div>

                <div class="input-field">
                    <input placeholder="活动" id="activity" name="activity" type="text" class="validate" required>
                </div>

                <div class="input-field">
                    <input placeholder="手机号" id="phone" name="phone" type="text" class="validate" pattern="[0-9]{11}">
                </div>

                <div class="row">
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 pl-0 tm-pr-xs-0">
                        <select name="department" required>
                            <option value="">部门</option>
                            <option value="办公室">办公室</option>
                            <option value="科创部">科创部</option>
                            <option value="外联部">外联部</option>
                            <option value="网信部">网信部</option>
                            <option value="宣传部">宣传部</option>
                            <option value="项管部">项管部</option>
                        </select>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 pl-0 tm-pr-xs-0">
                        <select name="department_job" required>
                            <option value="">职务</option>
                            <option value="部长">部长</option>
                            <option value="副部长">副部长</option>
                            <option value="干事">干事</option>
                            <option value="主席">主席</option>
                            <option value="副主席">副主席</option>
                        </select>
                    </div>
                </div>
                <div class="text-right mt-4">
                    <button type="submit" class="waves-effect btn-large btn-large-white px-4 black-text"><b>提交</b></button>
                </div>
            </form>
        </div>
        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 tm-register-col-r">
            <header class="mb-5">
                <h3 class="mt-0 text-white">科仔信息系统</h3>
                <p class="grey-text">为方便日后工作管理，现收集科协成员基本信息，请如实填写。</p>
                <p class="grey-text">如果提交后意识到信息有误，请联系部长修改。</p>
            </header>

        </div>
    </div>
    <footer class="row tm-mt-big mb-3">
        <div class="col-xl-12">
            <p class="text-center grey-text text-lighten-2 tm-footer-text-small">
                友情链接-<a href="http://tw.cczu.edu.cn/dxskx/main.htm" target="_blank" title="科协官网">科协官网</a>
                <br>
                本系统由校科协网信部提供技术支持~
            </p>
        </div>
    </footer>
</div>

<script src="{% static '/form_1/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static '/form_1/js/materialize.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>
</body>

</html>

templates/new_person.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>校科协招新线上报名</title>

    {% load static %}
    <link rel="stylesheet" href="{% static "form_1/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "form_1/css/materialize.min.css" %}">
    <link rel="stylesheet" href="{% static "form_1/css/tooplate.css" %}">
</head>

<body id="application" style="background-image: url({% static 'form_1/img/input-bg-03.jpg' %})">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mt-5 mb-5 text-center">
                    <h4><b>常州大学大学生科学技术协会</b></h4>
                    <h3><b>线上报名已截止</b></h3>
                    <p class="tm-form-description">Oops～ 很不巧，我们线上报名已经截止了，但是不要慌，来晚的小伙伴可以加QQ群：820201084联系管理员报名哦</p>
                </header>

            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                    为方便后续通知，请加入校科协招新群：820201084
                    <br>请各位萌新认真填写一下信息哦，填写完后检查无误后提交，重复提交无效。如有信息填错提交的，请联系招新群内管理员进行信息修改。谢谢合作，期待今后与你一起走过快乐的大学时光~
                    本系统由校科协网信部提供技术支持~
                </p>
            </div>
        </footer>
    </div>
</body>
</html>

templates/single_index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>校科协线上报名</title>

    <link rel="stylesheet" href="{% static 'form_1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/tooplate.css' %}">
</head>

<body id="application" style="background-image: url(/activity_submit{{ background_img.url }})">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mt-5 mb-5 text-center">
                    <h3><b>{{ name }}</b></h3>
                    <p class="tm-form-description">{{ introduction }}</p>
                    <p class="tm-form-description">{{ qq_num }}</p>
					<img width="200" src="/activity_submit{{ qq_QRcode.url }}" alt="二维码加载失败">
                </header>
                <form action="{% url 'activity_submit:index' %}" method="post" enctype="multipart/form-data" class="tm-form-white tm-font-big">
                    {% csrf_token %}
                    <input id="id_teammate" name="teammate" value="队长" hidden>
                    <div class="tm-bg-white tm-form-pad-big center">
						<button type="submit" class="waves-effect btn-large btn-large-white">开始报名</button>
					</div>
                </form>
            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                    欢迎加入科协大家庭，深入了解请访问-
					<a href="http://tw.cczu.edu.cn/dxskx/main.htm" target="_blank" title="科协官网">科协官网</a></p>
            </div>
        </footer>
    </div>

</body>

</html>

templates/submit_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>校科协线上报名</title>

    <link rel="stylesheet" href="{% static 'form_1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/tooplate.css' %}">
</head>

<body id="application" style="background-image: url(/activity_submit{{ background_img.url }})">
<div class="container">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
            <header class="mt-5 mb-5 text-center">
                <h3><b>{{ title }}</b></h3>
                <p class="tm-form-description">{{ context }}</p>
                {% if error_message %}
                    <p class="tm-form-description" style="color: red">{{ error_message }}</p>
                {% endif %}
            </header>
            <form action="{% url 'submit_form' teammate %}" method="post" enctype="multipart/form-data" class="tm-form-white tm-font-big">
                {% csrf_token %}
                <div class="tm-bg-white tm-form-pad-big">
                    <div class="form-group mb-5">
                        <b><label for="name" class="black-text mb-4 big">姓名：</label></b>
                        <input id="id_name" name="name" type="text" class="validate tm-input-white-bg" required>
                    </div>

                    <div class="form-group mb-5">
                        <b><label for="class_num" class="black-text mb-4 big" lay-search>学院：</label></b>
                        <select id="id_academy" name="academy" required>
                            <option value="">---请选择学院---</option>
                            {% for aca in academy %}
                                <option value="{{ aca.academy }}">{{ aca.academy }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group mb-5">
                        <b><label for="class_num" class="black-text mb-4 big">专业：</label></b>
                        <select id="id_class_name" name="class_name" required>
                            <option value="">---请选择专业---</option>
                        </select>
                    </div>
                    <div class="form-group mb-5">
                        <b><label for="class_num" class="black-text mb-4 big">班号：</label></b>
                        <input id="id_class_num" name="class_num" type="text" class="validate tm-input-white-bg" required pattern="[0-9]{3}">
                    </div>
                    {# 只有队员才会显示队伍号框 #}
                    {% if teammate == '队员' %}
                        <div class="form-group mb-5">
                            <b><label for="class_num" class="black-text mb-4 big">队伍号：</label></b>
                            <input id="id_team_id" name="team_id" type="text" class="validate tm-input-white-bg" required>
                        </div>
                    {% endif %}
                    <div class="form-group mb-5">
                        <b><label for="stu_id" class="black-text mb-4 big">学号：</label></b>
                        <input id="id_stu_id" name="stu_id" type="text" class="validate tm-input-white-bg mb-4" required pattern="[0-9]{8}">
                    </div>
                    <div class="form-group mb-5">
                        <b><label for="phone" class="black-text mb-4 big">手机号：</label></b>
                        <input id="id_phone" name="phone" type="text" class="validate tm-input-white-bg mb-4" required pattern="[0-9]{11}">
                    </div>
                    <div class="form-group mb-5">
                        <b><label for="qq_num" class="black-text mb-4 big">QQ号：</label></b>
                        <input id="id_qq_num" name="qq_num" type="text" class="validate tm-input-white-bg mb-4" required>
                    </div>
                </div>
                <div class="text-center mt-5">
                    <button type="submit" class="waves-effect btn-large btn-large-white"><b>提交</b></button>
                </div>
            </form>
        </div>
    </div>
    <footer class="row tm-mt-big mb-3">
        <div class="col-xl-12 text-center">
            <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                欢迎加入科协大家庭，深入了解请访问-
                <a href="http://tw.cczu.edu.cn/dxskx/main.htm" target="_blank" title="科协官网">科协官网</a></p>
        </div>
    </footer>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="{% static '/form_1/js/materialize.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('select').formSelect();
    });
</script>

<script>
    $(function () {
        $("#id_academy").change(function () {
            $.getJSON('{% url 'ajax_get' %}', {academy: $(this).val()}, function (json, TextStatus) {
                //先清空
                $("#id_class_name").empty().append('<option value="">---请选择专业---</option>');
                $('id_class_name').formSelect();
                var options = '';
                for (var i = 0; i < json.length; i++) {
                    options += '<option value="' + json[i]['class_name'] + '">' + json[i]['class_name'] + '</option>';
                    //alert(options);
                }
                $("#id_class_name").prepend(options);
                $('#id_class_name').formSelect();
            })
        })
    })
</script>

</body>

</html>

templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>报名成功</title>
	
    <link rel="stylesheet" href="{% static 'form_1/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'form_1/css/tooplate.css' %}">
</head>

<body id="application" style="background-image: url(/activity_submit{{ background_img.url }})">
    <div class="container">
        <div class="row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mt-5 mb-5 text-center">
                    <h3><b>报名成功</b></h3>
                    <p class="tm-form-description">{{ academy }} {{ class_num }}班的{{ name }}同学,</p>
                    <p class="tm-form-description">恭喜你报名成功！</p>
                    <p class="tm-form-description">你的队伍号是{{ team_id }}</p>
                    <p class="tm-form-description">你的队伍成员有：</p>
                    {% for teammate_name in teammate_names %}
                        <p class="tm-form-description">{{ teammate_name.name }}</p>
                    {% endfor %}
                    <p class="tm-form-description">如果以上信息有误，请联系管理员修改～</p>
                    <br>
                    <p class="tm-form-description">QQ群号</p>
					<img width="200" src="/activity_submit{{ qq_QRcode.url }}" alt="二维码加载失败">
                </header>
            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-black white-text py-2 tm-px-5">
                    欢迎加入科协大家庭，深入了解请访问-
					<a href="http://tw.cczu.edu.cn/dxskx/main.htm" target="_blank" title="科协官网">科协官网</a></p>
            </div>
        </footer>
    </div>

</body>

</html>

templates/thanks.html
<!DOCTYPE html>
<html lang="en">
        <head>
                <meta charset="UTF-8">
                <title>感谢</title>
        </head>

        <body>
                <center>
                        {% csrf_token %}
                        <h1>感谢填写！提交成功</h1>
                </center>
        </body>
</html>